"""
Name: Madeline Boss, Mahi Agrawal
Date: 11/13/25
Assignment: 5
Due Date: November 20, 2025
About this project: The goal of this project is to develop a web app with a web frontend and a database backend for small 
scale real-world applications using Flask and Python
Assumptions: Provided code from professor works.
All work below was performed solely by Madeline Boss and Mahi Agrawal.
I did not use code generated by an AI tool.
"""

import sqlite3
from flask import Flask, render_template, request, session, redirect, url_for
app = Flask(__name__)

app.secret_key = "baking-contest-key"

def init_db():
	# connecting to database
	conn = sqlite3.connect('./assignment5.db')
	# creating cursor to execute queries
	cur = conn.cursor()
	# creating the users table if it does not already exist
	cur.execute('''CREATE TABLE IF NOT EXISTS users(
	Name TEXT NOT NULL,
	Age INTEGER NOT NULL,
	PhoneNum INTEGER NOT NULL,
	SecLvl INTEGER NOT NULL,
	Password TEXT NOT NULL
	);''')
	conn.commit()
	cur.execute('''CREATE TABLE IF NOT EXISTS results(
			 EntryID INTEGER NOT NULL, 
			 UserID INTEGER NOT NULL, 
			 BakedItem TEXT NOT NULL,
			 ExcelVotes INTEGER NOT NULL, 
			 OkayVotes INTEGER NOT NULL, 
			 BadVotes INTEGER NOT NULL);
	''')
	conn.commit()
	conn.close()
	
def get_db():
	conn = sqlite3.connect('./assignment5.db')
	conn.row_factory = sqlite3.Row
	return conn

	
# homepage
@app.route('/')
def home():
	if not session.get('logged_in'):
		return render_template('login.html')

	return render_template('home.html', username=session['username'], security=session['security'])

# login page
@app.route('/login', methods=['GET', 'POST'])
def login():
	if request.method == 'GET':
		return render_template('login.html')

	elif request.method == 'POST':

		# get input values from html form
		username = request.form.get("username", "").strip()
		password = request.form.get("password", "").strip()

		# validate username and password against user database
		conn = get_db()
		cur = conn.cursor()
		cur.execute("SELECT * FROM users WHERE Name=? AND Password=?", (username, password))
		user = cur.fetchone()
		conn.close()

		if user == None:
			return render_template('login.html', error="Invalid username and/or password!")
		else:
			session['logged_in'] = True
			session['username'] = user['Name']
			session['security'] = user['SecLvl']

			return redirect(url_for('home'))

# add new baking contest user
@app.route('/addNewUser', methods=['GET', 'POST'])
def addNewUser():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	if request.method == 'GET':
		return render_template('new-baking-user.html')

	elif request.method == 'POST':

		# get input values from html form
		name = request.form.get("name", "").strip()
		age = request.form.get("age", "").strip()
		phoneNum = request.form.get("phone", "").strip()
		securityLevel = request.form.get("security", "").strip()
		password = request.form.get("password", "").strip()

		# validate input values
		error_messages = []

		if name == "":
			error_messages.append("You can not enter an empty name.")
		if not age.isdigit():
			error_messages.append("Age must be a whole number.")
		else:
			age = int(age)
			if age <= 0 or age >= 121:
				error_messages.append("Age must be greater than 0 and less than 121.")
		if phoneNum == "":
			error_messages.append("You can not enter enter an empty phone number.")
		if not securityLevel.isdigit():
			error_messages.append("Security level must be a whole number.")
		else:
			securityLevel = int(securityLevel)
			if securityLevel < 1 or securityLevel > 3:
				error_messages.append("Security level must be between 1 and 3.")
		if password == "":
			error_messages.append("You can not enter an empty password.")

		# if error messages exist, print them on the results page
		if error_messages:
			return render_template('results.html', message=error_messages)

		# add new user into database using a parameterized query
		conn = sqlite3.connect('./assignment5.db')
		cur = conn.cursor()
		cur.execute(
			"INSERT INTO users (Name, Age, PhoneNum, SecLvl, Password) VALUES (?, ?, ?, ?, ?)",
			(name, age, phoneNum, securityLevel, password)
		)
		conn.commit()
		conn.close()

		# return success message (THE RESULTS PAGE IS THE SUCCESS/ERROR MESSAGES)
		return render_template('results.html', message=["User added successfully."])


# list baking contest users
@app.route('/listUsers')
def listUsers():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	conn = get_db()
	cur = conn.cursor()
	cur.execute('SELECT * from users')
	users = cur.fetchall()
	conn.close()
	return render_template('list-baking-users.html', users = users)


# list baking contest results
@app.route('/listResults')
def listResults():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	conn = get_db()
	cur = conn.cursor()
	cur.execute("SELECT COUNT(*) FROM results")
	count = cur.fetchone()[0]
	result = []
	if count == 0:
		result = [('1', '1', 'Whoot Whoot Brownies', '1', '2', '4'),
			 ('2', '2', 'Cho Chip Cookies', '4', '1', '2'), 
			 ('3', '3', 'Cho Cake', '2', '4', '1'),
			 ('4', '1', 'Sugar Cookies', '2', '2', '1')]
	cur.executemany('Insert Into results Values (?,?,?,?,?,?)', result)
	conn.commit()
	
    #fetching data
	cur.execute("SELECT * FROM results")
	results = cur.fetchall()
	conn.close()
	return render_template('list-results.html', results=results)

# logout
@app.route('/logout')
def logout():
	session.clear()
	return redirect(url_for('login'))


if __name__ == '__main__':
	init_db()
	app.run(host='127.0.0.1', port=50000)
	# visit http://127.0.0.1:50000 to see website
