"""
Name: Madeline Boss, Mahi Agrawal
Date: 11/13/25
Assignment: 5
Due Date: November 20, 2025
About this project: The goal of this project is to develop a web app with a web frontend and a database backend for small 
scale real-world applications using Flask and Python
Assumptions: Provided code from professor works.
All work below was performed solely by Madeline Boss and Mahi Agrawal.
I did not use code generated by an AI tool.
"""

import sqlite3
from Crypto.Cipher import AES
import  string,base64
from flask import Flask, render_template, request, session, redirect, url_for
app = Flask(__name__)

app.secret_key = "baking-contest-key"

class AESCipher(object):
    def __init__(self, key,iv):
        self.key = key
        self.iv = iv

    def encrypt(self, raw):
        self.cipher = AES.new(self.key, AES.MODE_CFB,self.iv)
        ciphertext = self.cipher.encrypt(raw)
        encoded = base64.b64encode(ciphertext)
        return encoded

    def decrypt(self, raw):
        decoded = base64.b64decode(raw)
        self.cipher = AES.new(self.key, AES.MODE_CFB,self.iv)
        decrypted = self.cipher.decrypt(decoded)
        return str(decrypted, 'utf-8')

def init_db():
	key = b'BLhgpCL81fdLBk23HkZp8BgbT913cqt0'
	iv = b'OWFJATh1Zowac2xr'
	cipher = AESCipher(key,iv)

	name = "Tom"
	age = 22
	phone = "1231231111"
	sec = 3
	password = "admin"

	encryptedName = cipher.encrypt(name.encode("utf-8"))
	encryptedPhone = cipher.encrypt(phone.encode("utf-8"))
	encryptedPass = cipher.encrypt(password.encode("utf-8"))

	# connecting to database
	conn = sqlite3.connect('./assignment5.db')
	# creating cursor to execute queries
	cur = conn.cursor()
	# creating the users table if it does not already exist
	cur.execute('''CREATE TABLE IF NOT EXISTS users(
	userID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Age INTEGER NOT NULL,
	PhoneNum TEXT NOT NULL,
	SecLvl INTEGER NOT NULL,
	Password TEXT NOT NULL
	);''')
	conn.commit()
	cur.execute('''CREATE TABLE IF NOT EXISTS results(
			 EntryID INTEGER NOT NULL, 
			 UserID INTEGER NOT NULL, 
			 BakedItem TEXT NOT NULL,
			 ExcelVotes INTEGER NOT NULL, 
			 OkayVotes INTEGER NOT NULL, 
			 BadVotes INTEGER NOT NULL);
	''')

	# check if Tom (admin) already exists
	cur.execute("SELECT * FROM users WHERE Name = ?", (encryptedName,))
	existing = cur.fetchone()

	# only insert if not already present
	if existing is None:
	    cur.execute(
	        "INSERT INTO users (Name, Age, PhoneNum, SecLvl, Password) VALUES (?, ?, ?, ?, ?)",
	        (encryptedName, age, encryptedPhone, sec, encryptedPass)
	    )
	    conn.commit()

	cur.execute('''CREATE TABLE IF NOT EXISTS entries(
			entryID INTEGER PRIMARY KEY AUTOINCREMENT, 
			userName TEXT NOT NULL, 
			item TEXT NOT NULL, 
			excellent INTEGER NOT NULL, 
			ok INTEGER NOT NULL, 
			bad INTEGER NOT NULL);''')
	conn.commit()
	conn.close()

def get_db():
	conn = sqlite3.connect('./assignment5.db')
	conn.row_factory = sqlite3.Row
	return conn

# homepage
@app.route('/')
def home():
	if not session.get('logged_in'):
		return render_template('login.html')

	return render_template('home.html', username=session['username'], security=session['security'])

# login page
@app.route('/login', methods=['GET', 'POST'])
def login():
	if request.method == 'GET':
		return render_template('login.html')

	elif request.method == 'POST':

		# get input values from html form
		username = request.form.get("username", "").strip()
		password = request.form.get("password", "").strip()
		key = b'BLhgpCL81fdLBk23HkZp8BgbT913cqt0'
		iv = b'OWFJATh1Zowac2xr'
		cipher = AESCipher(key,iv)

		encrypt_user = cipher.encrypt(username.encode("utf-8"))
		encrypt_pass = cipher.encrypt(password.encode('utf-8'))

		# validate username and password against user database
		conn = get_db()
		cur = conn.cursor()
		cur.execute("SELECT * FROM users WHERE Name=? AND Password=?", (encrypt_user, encrypt_pass))
		user = cur.fetchone()
		conn.close()

		if user == None:
			return render_template('login.html', error="Invalid username and/or password!")
		else:
			session['logged_in'] = True
			session['username'] = cipher.decrypt(user['Name'])
			session['security'] = user['SecLvl']

			return redirect(url_for('home'))

# add new baking contest user
@app.route('/addNewUser', methods=['GET', 'POST'])
def addNewUser():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	if session.get('security') != 3:
		not_found_msg = ["The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."]
		return render_template('not-found.html', message=not_found_msg)
		
	if request.method == 'GET':
		return render_template('new-baking-user.html')

	elif request.method == 'POST':

		# get input values from html form
		name = request.form.get("name", "").strip()
		age = request.form.get("age", "").strip()
		phoneNum = request.form.get("phone", "").strip()
		securityLevel = request.form.get("security", "").strip()
		password = request.form.get("password", "").strip()

		# validate input values
		error_messages = []

		if name == "":
			error_messages.append("You can not enter an empty name.")
		if not age.isdigit():
			error_messages.append("Age must be a whole number.")
		else:
			age = int(age)
			if age <= 0 or age >= 121:
				error_messages.append("Age must be greater than 0 and less than 121.")
		if phoneNum == "":
			error_messages.append("You can not enter enter an empty phone number.")
		if not securityLevel.isdigit():
			error_messages.append("Security level must be a whole number.")
		else:
			securityLevel = int(securityLevel)
			if securityLevel < 1 or securityLevel > 3:
				error_messages.append("Security level must be between 1 and 3.")
		if password == "":
			error_messages.append("You can not enter an empty password.")

		# if error messages exist, print them on the results page
		if error_messages:
			return render_template('results.html', message=error_messages)

		#encryption
		key = b'BLhgpCL81fdLBk23HkZp8BgbT913cqt0'
		iv = b'OWFJATh1Zowac2xr'
		cipher = AESCipher(key,iv)

		encryptedName = cipher.encrypt(name.encode("utf-8"))
		encryptedPhone = cipher.encrypt(phoneNum.encode("utf-8"))
		encryptedPass = cipher.encrypt(password.encode("utf-8"))
		# add new user into database using a parameterized query
		conn = sqlite3.connect('./assignment5.db')
		cur = conn.cursor()
		cur.execute(
			"INSERT INTO users (Name, Age, PhoneNum, SecLvl, Password) VALUES (?, ?, ?, ?, ?)",
			(encryptedName, age, encryptedPhone, securityLevel, encryptedPass)
		)
		conn.commit()
		conn.close()

		# return success message (THE RESULTS PAGE IS THE SUCCESS/ERROR MESSAGES)
		return render_template('results.html', message=["User added successfully."])


# list baking contest users
@app.route('/listUsers')
def listUsers():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	if session.get('security') < 2:
		not_found_msg = ["The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."]
		return render_template('not-found.html', message=not_found_msg)
	
	conn = get_db()
	cur = conn.cursor()
	cur.execute('SELECT * from users')
	users_encrypt = cur.fetchall()
	conn.close()
	#decryption
	key = b'BLhgpCL81fdLBk23HkZp8BgbT913cqt0'
	iv = b'OWFJATh1Zowac2xr'
	cipher = AESCipher(key,iv)

	#decrypted users list
	users_decrypt = []
	for u in users_encrypt:
		users_decrypt.append({
			'Name': cipher.decrypt(u['Name']),
			'Age': u['Age'],
			'PhoneNum': cipher.decrypt(u['PhoneNum']),
			'SecLvl': u['SecLvl'],
			'Password': cipher.decrypt(u['Password'])
		})
	return render_template('list-baking-users.html', users = users_decrypt)


# list baking contest results
@app.route('/listResults')
def listResults():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	if session.get('security') != 3:
		not_found_msg = ["The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."]
		return render_template('not-found.html', message=not_found_msg)
	
	conn = get_db()
	cur = conn.cursor()
	cur.execute("SELECT COUNT(*) FROM results")
	count = cur.fetchone()[0]
	result = []
	if count == 0:
		result = [('1', '1', 'Whoot Whoot Brownies', '1', '2', '4'),
			 ('2', '2', 'Cho Chip Cookies', '4', '1', '2'), 
			 ('3', '3', 'Cho Cake', '2', '4', '1'),
			 ('4', '1', 'Sugar Cookies', '2', '2', '1')]
		cur.executemany('Insert Into results Values (?,?,?,?,?,?)', result)
		conn.commit()
	
	#fetching data
	cur.execute("SELECT * FROM entries")
	results = cur.fetchall()
	conn.close()
	return render_template('list-results.html', results=results)

# logout
@app.route('/logout')
def logout():
	session.clear()
	return redirect(url_for('login'))

@app.route('/new-entry', methods=['GET', 'POST'])
def newEntry():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	if request.method == 'GET':
		return render_template('new-entry.html')
	
	elif request.method == 'POST':
		#grabbing input vals from the web page
		bakingItem = request.form.get("nameItem", "").strip()
		excellent = request.form.get("excelVote", "").strip()
		ok = request.form.get("okVotes", "").strip()
		bad = request.form.get("badVotes", "").strip()

		#valitading user inputs
		error_msgs = []

		if bakingItem == "":
			error_msgs.append("You cannot enter an empty name of baking item.")
		
		if not excellent.isdigit():
			error_msgs.append("Number of excellent votes must be a whole number.")

		else:
			excellent = int(excellent)
			if excellent < 0:
				error_msgs.append("Number of excellent votes cannot be less than zero.")
		
		if not ok.isdigit():
			error_msgs.append("Number of OK votes must be a whole number.")

		else:
			ok = int(ok)
			if ok < 0:
				error_msgs.append("Number of OK votes cannot be less than zero.")

		if not bad.isdigit():
			error_msgs.append("Number of bad votes must be a whole number.")

		else:
			bad = int(bad)
			if bad < 0:
				error_msgs.append("Number of bad votes cannot be less than zero.")

		if error_msgs:
			return render_template('results.html', message=error_msgs)
		
		conn = sqlite3.connect('./assignment5.db')
		cur = conn.cursor()
		cur.execute(
			"INSERT INTO entries (userName, item, excellent, ok, bad) VALUES (?, ?, ?, ?, ?)",
			(session['username'], bakingItem, excellent, ok, bad)
		)
		conn.commit()
		conn.close()

		return render_template('results.html', message = ["Baking contest entry successfully added."])

@app.route('/my-results')
def myResults():
	if not session.get('logged_in'):
		return render_template('login.html')
	
	username = session['username']
	conn = sqlite3.connect('./assignment5.db')
	conn.row_factory = sqlite3.Row
	cur = conn.cursor()
	cur.execute("SELECT * FROM entries WHERE userName = ?",
			 (username, ))
	user_entries = cur.fetchall()
	conn.close()
	return render_template('my-results.html', entries=user_entries)


@app.route('/results')
def results():
	return render_template('results.html')

@app.route('/not-found')
def notFound():
	return render_template('not-found.html')

if __name__ == '__main__':
	init_db()
	app.run(host='127.0.0.1', port=50000)
	# visit http://127.0.0.1:50000 to see website
