"""
Name: Madeline Boss, Mahi Agrawal
Date: 11/13/25
Assignment: 5
Due Date: November 20, 2025
About this project: The goal of this project is to develop a web app with a web frontend and a database backend for small 
scale real-world applications using Flask and Python
Assumptions: Provided code from professor works.
All work below was performed solely by Madeline Boss and Mahi Agrawal.
I did not use code generated by an AI tool.
"""

import sqlite3
from flask import Flask
app = Flask(__name__)

#homepage
@app.route('/')
def home():
    return 'Hello World'

if __name__ == '__main__':
    app.run(host='127.0.0.1', port = 50000)
    #visit http://127.0.0.1:50000 to see website