"""
Name: Madeline Boss, Mahi Agrawal
Date: 11/13/25
Assignment: 5
Due Date: November 20, 2025
About this project: The goal of this project is to develop a web app with a web frontend and a database backend for small 
scale real-world applications using Flask and Python
Assumptions: Provided code from professor works.
All work below was performed solely by Madeline Boss and Mahi Agrawal.
I did not use code generated by an AI tool.
"""

import sqlite3
from flask import Flask
app = Flask(__name__)

#homepage
@app.route('/')
def home():
    return 'This is the home page'

    '''
	Link - Add new Baking Contest User - (opens the add a New Baking Contest User page)
	Link - List Baking Contest Users - (opens the List Baking Contest Users page)
	Link - Baking Contest Results - (opens the list Contest Results page)
    '''

@app.route('/addNewUser')
def openAddNewUserPage():
	return 'This is the add new baking contest user page'

@app.route('/listUsers')
def listUsersPage():
	return 'This is the list baking contest users page'

@app.route('/listResults')
def listResults():
	return 'This is the list contest results page.'

if __name__ == '__main__':
    app.run(host='127.0.0.1', port = 50000)
    #visit http://127.0.0.1:50000 to see website